version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
    restart: unless-stopped
    container_name: test_app
    volumes:
      - quiz_results:/app/data

volumes:
  quiz_results:
